language: node_js
nodejs:
- node
deploy:
  provider: heroku
  app: send-app
  strategy: git
  cache: node_modules
  api_key:
    secure: SVVznGV5PL3aME7S15Oo9T73jdtyC+xggVANOi4e3T3GPcyxOBlZyP5MMYNLeGmV5peZJPRZ5Aa++MwWIhlGlLbyxhXcYF6DkwW0U33aNZvlvx1KJtx4KpIrQq/fdtfK54LgX3baNEDt9ebxk/vfbqWVFz0n7rKZfZDlGxaPOm/4cwUzK71WRp6HmJu639h9vFyEwGGrGKNUC9AlWfqZm4lTFljnJ33aYb580jqNluNqT/siIB845TfeGGPcas69wBL1gRSt1J+uAuGBz5/Id3yMfNVkZkhIhANuTKUhsiFSVoEdBQTGY1OVvspOGMTOAQGVu8cYbGuHdijpNEdLg0iqTYRHu01O1v5mnooZk0xuld9eD/ujfZtmZdUWvxEm4SUDu+CU6CYoNgErzTeU1kX78dJtGq/mnLBRjI0WpYl4O6XGwbhlwBTPyvgGmQOqYi0JzvZVPaePQAkDmqJ8i7LDLl0hhLwKEkQwmFDcpWI9ULVTO/X0Oxy5G35u2pqjq/BzH+CTkUpGAoeVli42Hq+OJIj3fLKuuX8XqlTJvg3KabJXUOgClvIgiQjNYKJUtXHLYsqLLLsU/8mtmdnI3mru9mpZQx87L1Z63KU/ZIqGhdjGIDdQAfqC2Hx76yakVNUnMMJoZwSgzFDodvWMNAnyy50Xwn2R9Sluxx7sfPI=
before_script:
- npm install
