language: node_js
nodejs:
- node
deploy:
  provider: heroku
  app: send-app
  strategy: git
  cache: node_modules
  api_key:

    secure: TUAcFTCU9IzZhBoShXIBEEX9iy5FYK7otTvlKQ6QbQrwGBQ5JSSLIzElCNR8b5pQ9X26QheTqgtn8/t0gNou3zab6q3WdC1BWbAyQ1tjKV7DNfl23UdUgJwtW1KAFEUn3MHCinBnjzqPb72PtmtZJiHmo85/KQlu1FAmry/Dt5FrzMyEcgMthGuQddTPGLNBO4g3uNdjGk8WiKDqFvj1Fl1cxR9S6OmFdZvAAkdazOZeL3vgtmTypUuKBed+4fUUAwm5Tlvndd+5P3VNuS2jcOhgecANq/8ziV8k19COHLxtk//uHYE2kfbLjBFvcE4njwEB4hNl6Iia4H6Ur4906hSPzinqXPbyaEisxDkiXCrQoasMEd/hrUSoHxba2ALHOcTTi1HwDyL0nvZLZ/cRC4qAj9vBozoSwLamuDJkSmWhZIC/NwPjT16IBjHcAsgThNG6OdB+3PDRM2Vmx2T/xXYvmsap6rbapWVteyljezHCNCnPwKHxnrc0dycNFuILLnB0cDPZ0Mlo8WE70FKPnFKCXINdRSCwrx/GIfZQYfxb0RVxwEIaaI0rlFeb+MJ6VJy8rRTbHIXwyL5mZWQ0lNyQWOX1faW+4zB4XEn3ykk3eGv01KCFYs+SQG5QVWbsa573wKSFaBqEuOkULm28nxRIax9zrKIrvNgduX9FjHQ=
script: npm run coverage
after_success: npm run coveralls

