language: node_js
nodejs:
- node
deploy:
  provider: heroku
  app: send-app
  strategy: git
  on: develop-review
  api_key:
    secure: t3WOGhEFgFVBkoXEjAfbb5ViAcoL4SF0yBSj0pxOa5lJ3//kQzVaumj0DUhys3uIWbXBILqhrXqbTvsJmKTzevg9bU6wuVg35AWxb9dZKvzWIFIhEHcg8w8url+hPq+G/2AYQiwH6ZVEnMjReWSwqh9j8S0kELqza6A976PLewlVODPDknceCxAtA7E01roHTauI7jOw5Tt87a6HULiDFVSMKkxBt73EnDFVQFzDdeRxCx/gH/k0+tnQeSUEguDaJKdItkjdPn0sZ8dF/8Q5HHB0XqKlify5k00Xn81hs6wJGcohN74xJoYH9VO+R7WBs1vdXmESu6/5hYnf/Hy5+ZY6pw82bM0QBhflIFedYTV6VA6tfE+m+WaHiLiwenyOHuGaGHmfIWUNVzbBecWSfq5LEj6osU19pOtDThOs89KaSXgZ5LzDVwlyof36fKkr5haiFMDf6gJDKv2NooqmfDmlQhFgZKAYBC1VX5h7+lY4CFDK36URJhJp5z9GdwhRgrYDt+yJ9Oec15Wu8NGD/+b6baRL8TupgpQNuSBA88aTHgvC/wr3Rrlwd1vy1b5lSVRqEXHb0Y6nY3bFQb2EfnoeFPSfhOEwv51f3fwfLUu91U0a2zSHzpxN6B2FquYLQsNnafOWXmeoXd8vZkinwV0D/kyQPRIl9qlnkP/+4Hc=
before_script:
- npm install
